export const reservationData = [
  {
    id: crypto.randomUUID(),
    clientName: "David",
    phoneNumber: "010-1234-4567",
    reservedDate: new Date(2023, 9, 22, 14, 0),
    personCount: 4,
    reservedTableCount: [7, 8],
    reservedFloor: 1,
    notes: "Birthday",
  },
  {
    id: crypto.randomUUID(),
    clientName: "Jason",
    phoneNumber: "010-1234-4567",
    reservedDate: new Date(2023, 9, 22, 15, 30),
    personCount: 3,
    reservedTableCount: 8,
    reservedFloor: 1,
    notes: "Note",
  },
  {
    id: crypto.randomUUID(),
    clientName: "Olivia",
    phoneNumber: "010-1234-4567",
    reservedDate: new Date(2023, 9, 22, 15, 0),
    personCount: 5,
    reservedTableCount: 7,
    reservedFloor: 1,
    notes: "Note",
  },
  {
    id: crypto.randomUUID(),
    clientName: "Mary",
    phoneNumber: "010-1234-4567",
    reservedDate: new Date(2023, 10, 1, 18, 0),
    personCount: 1,
    reservedTableCount: undefined,
    reservedFloor: undefined,
    notes: undefined,
  },
  {
    id: crypto.randomUUID(),
    clientName: "Ash",
    phoneNumber: "010-1234-4567",
    reservedDate: new Date(2023, 10, 2, 17, 0),
    personCount: 1,
    reservedTableCount: undefined,
    reservedFloor: undefined,
    notes: undefined,
  },
];
